export const ComponentPropritiesOptions = {
  contentTypes: [
    { value: "none", label: "None" },
    { value: "text", label: "Text" },
    { value: "image", label: "Image" },
    { value: "link", label: "Link" },
    { value: "component", label: "Component" },
  ],
  size: [
    { value: "static", label: "Static" },
    { value: "100%", label: "Fill" },
    { value: "max-content", label: "Content" },
    { value: "auto", label: "Auto" },
  ],
  borderStyle: [
    { value: "none", label: "None" },
    { value: "solid", label: "Solid" },
    { value: "dashed", label: "Dashed" },
    { value: "dotted", label: "Dotted" },
    { value: "double", label: "Double" },
    { value: "groove", label: "Groove" },
    { value: "ridge", label: "Ridge" },
    { value: "inset", label: "Inset" },
    { value: "outset", label: "Outset" },
  ],
  display: [
    { value: "block", label: "Block" },
    { value: "inline", label: "Inline" },
    { value: "flex", label: "Flex" },
    { value: "grid", label: "Grid" },
  ],
  flexDirection: [
    { value: "row", label: "Row" },
    { value: "row-reverse", label: "Row Reverse" },
    { value: "column", label: "Column" },
    { value: "column-reverse", label: "Column Reverse" },
  ],
  flexWrap: [
    { value: "nowrap", label: "No Wrap" },
    { value: "wrap", label: "Wrap" },
    { value: "wrap-reverse", label: "Wrap Reverse" },
  ],
  justifyContent: [
    { value: "flex-start", label: "Flex Start" },
    { value: "flex-end", label: "Flex End" },
    { value: "center", label: "Center" },
    { value: "space-between", label: "Space Between" },
    { value: "space-around", label: "Space Around" },
    { value: "space-evenly", label: "Space Evenly" },
  ],
  alignItems: [
    { value: "flex-start", label: "Flex Start" },
    { value: "flex-end", label: "Flex End" },
    { value: "center", label: "Center" },
    { value: "baseline", label: "Baseline" },
  ],
  fontFamily: [
    { value: "Arial", label: "Arial" },
    { value: "Helvetica", label: "Helvetica" },
    { value: "Times New Roman", label: "Times New Roman" },
    { value: "Times", label: "Times" },
  ],
  fontWeight: [
    { value: "100", label: "100" },
    { value: "200", label: "200" },
    { value: "300", label: "300" },
    { value: "400", label: "400" },
    { value: "500", label: "500" },
    { value: "600", label: "600" },
    { value: "700", label: "700" },
  ],
  fontStyle: [
    { value: "normal", label: "Normal" },
    { value: "italic", label: "Italic" },
  ],
  textDecoration: [
    { value: "none", label: "None" },
    { value: "underline", label: "Underline" },
    { value: "overline", label: "Overline" },
    { value: "line-through", label: "Line Through" },
  ],
  textAlign: [
    { value: "left", label: "Left" },
    { value: "center", label: "Center" },
    { value: "right", label: "Right" },
    { value: "justify", label: "Justify" },
  ],
};
